p8105_hw6_xf2302
================
Xiuhong Fan
2025-11-30

# Problem 1

# Load packages and read local CSV

``` r
library(tidyverse)
```

    ## Warning: package 'ggplot2' was built under R version 4.5.2

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   4.0.1     ✔ tibble    3.3.0
    ## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
    ## ✔ purrr     1.1.0     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(broom)
library(purrr)
library(modelr)
```

    ## 
    ## Attaching package: 'modelr'
    ## 
    ## The following object is masked from 'package:broom':
    ## 
    ##     bootstrap

``` r
library(forcats)
library(rsample)
library(p8105.datasets)

homicides =
  read_csv("Data/homicide-data.csv")
```

    ## Rows: 52179 Columns: 12
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (9): uid, victim_last, victim_first, victim_race, victim_age, victim_sex...
    ## dbl (3): reported_date, lat, lon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

# Data cleaning

``` r
homicides_clean =
  homicides %>%
  mutate(
    city_state = str_c(city, state, sep = ", "),
    solved = if_else(disposition == "Closed by arrest", 1, 0),
    victim_age = as.numeric(victim_age)
  ) %>%
  filter(
    !city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL"),
    victim_race %in% c("White", "Black")
  )
```

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `victim_age = as.numeric(victim_age)`.
    ## Caused by warning:
    ## ! NAs introduced by coercion

# Baltimore logistic regression

``` r
baltimore_df =
  homicides_clean %>%
  filter(city_state == "Baltimore, MD")

baltimore_fit =
  glm(
    solved ~ victim_age + victim_sex + victim_race,
    data = baltimore_df,
    family = binomial()
  )

baltimore_results =
  tidy(baltimore_fit, conf.int = TRUE, exp = TRUE) %>%
  filter(term == "victim_sexMale") %>%
  select(estimate, conf.low, conf.high)

baltimore_results
```

    ## # A tibble: 1 × 3
    ##   estimate conf.low conf.high
    ##      <dbl>    <dbl>     <dbl>
    ## 1    0.426    0.324     0.558

For Baltimore, MD, the adjusted odds ratio comparing male to female
victims is 0.426, with a 95% confidence interval of 0.324 to 0.558. This
means that, after adjusting for victim age and race, homicides involving
male victims are significantly less likely to be solved than those
involving female victims. Because the confidence interval lies entirely
below 1, the association is statistically meaningful and indicates a
substantially lower clearance rate for male-victim homicides in
Baltimore.

# Fit glm for each city and extract OR

``` r
city_or_results =
  homicides_clean %>%
  nest(data = -city_state) %>%
  mutate(
    fit = map(
      data,
      ~ glm(
          solved ~ victim_age + victim_sex + victim_race,
          data = .x,
          family = binomial()
        )
    ),
    tidy_fit = map(fit, ~ tidy(.x, conf.int = TRUE, exp = TRUE))
  ) %>%
  unnest(tidy_fit) %>%
  filter(term == "victim_sexMale") %>%
  select(city_state, estimate, conf.low, conf.high)
```

    ## Warning: There were 43 warnings in `mutate()`.
    ## The first warning was:
    ## ℹ In argument: `tidy_fit = map(fit, ~tidy(.x, conf.int = TRUE, exp = TRUE))`.
    ## Caused by warning:
    ## ! glm.fit: fitted probabilities numerically 0 or 1 occurred
    ## ℹ Run `dplyr::last_dplyr_warnings()` to see the 42 remaining warnings.

# Forest plot of ORs across cities

``` r
city_or_plot =
  city_or_results %>%
  arrange(estimate) %>%
  mutate(city_state = factor(city_state, levels = city_state)) %>%
  ggplot(aes(x = estimate, y = city_state)) +
  geom_point() +
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), height = 0.2) +
  geom_vline(xintercept = 1, linetype = "dashed") +
  labs(
    x = "Adjusted Odds Ratio (Male vs Female Victims)",
    y = "City",
    title = "Adjusted Odds Ratios for Solving Homicides by City",
    subtitle = "Models adjust for victim age and race"
  ) +
  theme(
    axis.text.y = element_text(size = 6, colour = "black")   
  )
```

    ## Warning: `geom_errorbarh()` was deprecated in ggplot2 4.0.0.
    ## ℹ Please use the `orientation` argument of `geom_errorbar()` instead.
    ## This warning is displayed once every 8 hours.
    ## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
    ## generated.

``` r
city_or_plot
```

    ## `height` was translated to `width`.

![](p8105_hw6_xf2302_files/figure-gfm/unnamed-chunk-5-1.png)<!-- -->

Across the 50 cities, the estimated odds ratios span a broad range,
indicating substantial variability in the association between victim sex
and homicide clearance rates. However, most estimates fall below 1,
suggesting that homicides involving male victims are generally less
likely to be solved than those involving female victims after adjusting
for age and race. A small number of cities have odds ratios near or
above 1, although these estimates typically have wide confidence
intervals, reflecting limited sample sizes or greater statistical
uncertainty. Overall, the plot highlights considerable heterogeneity
across cities, but the prevailing pattern is that male-victim homicides
tend to exhibit lower clearance rates.

# Problem 2

# Functions for Model Fitting and Bootstrap Statistics

``` r
fit_lm <- function(df) {
  lm(tmax ~ tmin + prcp, data = df)
}

boot_fn <- function(df) {
  sample_df = df %>% sample_frac(replace = TRUE)
  fit = fit_lm(sample_df)
  
  r2 = glance(fit)$r.squared
  
  coef_df = tidy(fit)
  beta1 = coef_df$estimate[coef_df$term == "tmin"]
  beta2 = coef_df$estimate[coef_df$term == "prcp"]
  
  ratio = beta1 / beta2
  
  tibble(r2 = r2, ratio = ratio)
}

set.seed(123)

boot_results =
  tibble(rep = 1:5000) %>%
  mutate(
    out = map(rep, ~ boot_fn(weather_df))
  ) %>%
  unnest(out)
```

# Distribution plots

``` r
r2_plot =
  boot_results %>%
  ggplot(aes(x = r2)) +
  geom_histogram(bins = 40, fill = "skyblue", color = "white") +
  labs(
    title = "Bootstrap Distribution of hat(r)^2",
    x = expression(hat(r)^2),
    y = "Count"
  )

ratio_plot =
  boot_results %>%
  ggplot(aes(x = ratio)) +
  geom_histogram(bins = 40, fill = "lightgreen", color = "white") +
  labs(
    title = "Bootstrap Distribution of hat(beta)[1] / hat(beta)[2]",
    x = expression(hat(beta)[1] / hat(beta)[2]),
    y = "Count"
  )

r2_plot
```

![](p8105_hw6_xf2302_files/figure-gfm/unnamed-chunk-7-1.png)<!-- -->

``` r
ratio_plot
```

![](p8105_hw6_xf2302_files/figure-gfm/unnamed-chunk-7-2.png)<!-- -->

# 95% confidence intervals

``` r
r2_ci =
  boot_results %>%
  summarize(
    low = quantile(r2, 0.025),
    high = quantile(r2, 0.975)
  )

ratio_ci =
  boot_results %>%
  summarize(
    low = quantile(ratio, 0.025),
    high = quantile(ratio, 0.975)
  )

r2_ci
```

    ## # A tibble: 1 × 2
    ##     low  high
    ##   <dbl> <dbl>
    ## 1 0.934 0.947

``` r
ratio_ci
```

    ## # A tibble: 1 × 2
    ##     low  high
    ##   <dbl> <dbl>
    ## 1 -279. -125.

## Distribution of $\hat{r}^{2}$

The bootstrap distribution of $\hat{r}^{2}$ is tightly concentrated
around 0.94 with a narrow and nearly symmetric spread, indicating that
the linear regression model explains a consistent proportion of
variability in *tmax* even under repeated resampling.

The 95% bootstrap confidence interval ranges from 0.934 to 0.947,
showing that the model fit remains stable across bootstrap samples.

## Distribution of $\hat{\beta}_{1}/\hat{\beta}_{2}$

In contrast, the bootstrap distribution of the ratio
$\hat{\beta}_{1}/\hat{\beta}_{2}$ is much wider and strongly left-skewed
because the precipitation coefficient $\hat{\beta}_{2}$ is very small
and varies near zero, making the ratio highly unstable under resampling.

The 95% bootstrap confidence interval is \[-279.3, -125.3\], reflecting
substantial uncertainty and indicating that this ratio is not a reliable
or interpretable summary of the model.

# Problem 3

# Load and clean the data

``` r
birthweight = 
  read_csv("https://p8105.com/data/birthweight.csv") %>%
  janitor::clean_names() %>%
  mutate(
    babysex = factor(babysex, levels = c(1, 2), labels = c("male", "female")),
    frace   = factor(frace),
    mrace   = factor(mrace),
    malform = factor(malform, levels = c(0, 1), labels = c("absent", "present"))
  )
```

    ## Rows: 4342 Columns: 20
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (20): babysex, bhead, blength, bwt, delwt, fincome, frace, gaweeks, malf...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
# Check missing data
sum(is.na(birthweight))
```

    ## [1] 0

After cleaning and formatting the dataset, all variables are prepared
for regression analysis, and no missing data were detected.

# Proposed model

``` r
model_prop = 
  lm(bwt ~ blength + bhead + gaweeks + babysex + wtgain + ppbmi + smoken,
     data = birthweight)

tidy(model_prop)
```

    ## # A tibble: 8 × 5
    ##   term          estimate std.error statistic   p.value
    ##   <chr>            <dbl>     <dbl>     <dbl>     <dbl>
    ## 1 (Intercept)   -6206.      99.8      -62.2  0        
    ## 2 blength          79.5      2.07      38.4  4.49e-278
    ## 3 bhead           138.       3.54      38.8  2.06e-283
    ## 4 gaweeks          13.5      1.50       8.98 3.86e- 19
    ## 5 babysexfemale    32.4      8.75       3.70 2.16e-  4
    ## 6 wtgain            3.72     0.405      9.18 6.72e- 20
    ## 7 ppbmi             5.13     1.37       3.75 1.77e-  4
    ## 8 smoken           -2.00     0.583     -3.43 6.13e-  4

This proposed model includes infant size at birth (length and head
circumference), gestational age, maternal weight-related variables,
smoking, and sex. These predictors were selected based on domain
knowledge and their expected relevance to birthweight.

# Residuals vs Fitted Values

``` r
birth_plot_df =
  birthweight %>%
  add_predictions(model_prop) %>%
  add_residuals(model_prop)

birth_plot_df %>%
  ggplot(aes(x = pred, y = resid)) +
  geom_point(alpha = 0.25,) +
  geom_hline(yintercept = 0, color = "lightpink", linetype = "dashed", linewidth = 1) +
  geom_smooth(se = FALSE, color = "lightskyblue", linewidth = 1.2) +
  labs(
    title = "Residuals vs Fitted Values (Proposed Model)",
    x = "Fitted Birthweight (grams)",
    y = "Residuals"
  ) +
  theme_minimal(base_size = 13) +
  theme(
    plot.title = element_text(face = "bold"),
    panel.grid.minor = element_blank()
  )
```

    ## `geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = "cs")'

![](p8105_hw6_xf2302_files/figure-gfm/unnamed-chunk-11-1.png)<!-- -->

Overall, the residual plot indicates reasonably good model fit, with
residuals centered around zero and no severe violations of linear model
assumptions, though the slight curvature suggests that modest nonlinear
patterns remain.

# Model 1: Birth Length and Gestational Age as Predictors

``` r
model_main = lm(bwt ~ blength + gaweeks, data = birthweight)
```

# Model 2: Three-Way Interaction Among Head Circumference, Length, and Sex

``` r
model_inter = lm(bwt ~ bhead * blength * babysex, data = birthweight)
```

# Cross-Validation: Model Fitting and RMSE Computation

``` r
set.seed(123)

cv_df = crossv_mc(birthweight, 200)

cv_results =
  cv_df %>%
  mutate(
    train = map(train, as_tibble),
    test  = map(test,  as_tibble),

    fit_prop = map(train, ~ lm(bwt ~ blength + bhead + gaweeks + babysex +
                                 wtgain + ppbmi + smoken, data = .x)),
    fit_main = map(train, ~ lm(bwt ~ blength + gaweeks, data = .x)),
    fit_inter = map(train, ~ lm(bwt ~ bhead * blength * babysex, data = .x)),

    rmse_prop  = map2_dbl(fit_prop,  test, ~ rmse(.x, .y)),
    rmse_main  = map2_dbl(fit_main,  test, ~ rmse(.x, .y)),
    rmse_inter = map2_dbl(fit_inter, test, ~ rmse(.x, .y))
  ) %>%
  select(starts_with("rmse"))
```

# Summary of Cross-Validated RMSE

``` r
cv_summary =
  cv_results %>%
  summarize(
    Proposed     = mean(rmse_prop),
    Main_Effects = mean(rmse_main),
    Interaction  = mean(rmse_inter)
  )

cv_summary
```

    ## # A tibble: 1 × 3
    ##   Proposed Main_Effects Interaction
    ##      <dbl>        <dbl>       <dbl>
    ## 1     282.         331.        288.

# Cross-Validated RMSE Distribution

``` r
cv_results %>%
  pivot_longer(everything(),
               names_to = "model",
               values_to = "rmse",
               names_prefix = "rmse_") %>%
  mutate(model = recode(model,
                        "prop" = "Proposed Model",
                        "main" = "Main Effects",
                        "inter" = "Interactions")) %>%
  ggplot(aes(x = model, y = rmse, fill = model)) +
  geom_violin(alpha = 0.5) +
  labs(
    title = "Cross-Validated RMSE Comparison",
    x = "Model",
    y = "RMSE"
  ) +
  theme_minimal() +
  theme(legend.position = "none")
```

![](p8105_hw6_xf2302_files/figure-gfm/unnamed-chunk-16-1.png)<!-- -->

Based on the comparison of three candidate models, the proposed model
consistently demonstrated the best predictive performance. Monte Carlo
cross-validation with 200 splits showed that it achieved the lowest mean
RMSE and the most stable error distribution. The main-effects model
underperformed due to omitted predictors, while the full interaction
model exhibited greater error and variability, indicating overfitting.
Overall, the proposed model provides the strongest balance of accuracy
and interpretability for predicting birthweight.
